services:
  # Backend service for Python
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PORT=5000
      - RABBITMQ_USERNAME=username
      - RABBITMQ_PASSWORD=password
      # change it to a public domain when bought, and add in credentials.json file and update google OAuth Credentials
      - FRONTEND_SERVICE=localhost:3000 
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - worker
    restart: always
    networks:
      - my-network

  # Frontend service for React
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app # I have done volume mapping here, hence the frontend build gets affected in realTime
    environment:
    # change it to a public domain when bought, and add in credentials.json file and update google OAuth credentials
      - REACT_APP_BACKEND_SERVICE=localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    networks:
      - my-network

  # RabbitMQ service for the worker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_DEFAULT_USER=username
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - my-network

  # Service for the worker.py script
  worker:
    build:
      context: ./scripts
    volumes:
      - ./scripts:/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=username
      - RABBITMQ_PASSWORD=password
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - my-network

networks:
  my-network:
    driver: bridge