FROM python:3.8

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

# Set environment variables
ENV RABBITMQ_URL="rabbitmq://rabbitmq:5672/"

# Expose the port used by the backend service
EXPOSE 8000

# Start the backend service
CMD ["python", "app.py"]