FROM python:3.8-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && \
    apt-get install -y libgl1-mesa-glx curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy requirements and install dependencies
COPY backend/requirements.txt .
COPY backend/requirements-dev.txt .

# Copy shared package for development
COPY shared /app/shared

# Install shared package in editable mode for development
RUN pip install -e /app/shared

# Install other dependencies
RUN pip install -r requirements.txt
RUN pip install -r requirements-dev.txt

# Copy backend code
COPY backend/ /app/

# Install additional dependencies
RUN pip install multipart

# Set working directory
WORKDIR /app

# Expose the port used by the backend service
EXPOSE 5000

# Start the backend service
CMD ["python", "app.py"] 