FROM python:3.8

WORKDIR /app

# Copy shared package first
COPY shared /app/shared

# Install shared package
RUN pip install -e /app/shared

# Copy requirements and install dependencies
COPY backend/requirements.txt .
RUN pip install -r requirements.txt

# Copy backend code to backend subdirectory
COPY backend/ /app/backend/

# Install additional system dependencies
RUN apt-get update && \
    apt-get install -y libgl1-mesa-glx

RUN pip install multipart

# COPY /etc/ssl/certs/* /app/etc/ssl/certs

# COPY /etc/ssl/cert.pem /app/etc/ssl/cert.pem

# COPY /usr/local/share/ca-certificates/* /app/usr/local/share/ca-certificates

# RUN update-ca-certificates

# Set working directory to backend
WORKDIR /app/backend

# Expose the port used by the backend service
EXPOSE 5000

# Start the backend service
CMD ["python", "app.py"]